In [27]:
from tensorflow.keras.preprocessing.text import Tokenizer, one_hot

In [28]:
sent = ['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [29]:
# define vocabulary size

voc_size = 10000

In [30]:
# One hot encoding

one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[5557, 5493, 4812, 2591],
 [5557, 5493, 4812, 8247],
 [5557, 2586, 4812, 3810],
 [9233, 1159, 9599, 2870, 4347],
 [9233, 1159, 9599, 2870, 924],
 [2548, 5557, 7328, 4812, 6739],
 [9995, 1447, 524, 2870]]

In [31]:
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [32]:
import numpy as np

In [33]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 5557, 5493, 4812, 2591],
       [   0,    0,    0,    0, 5557, 5493, 4812, 8247],
       [   0,    0,    0,    0, 5557, 2586, 4812, 3810],
       [   0,    0,    0, 9233, 1159, 9599, 2870, 4347],
       [   0,    0,    0, 9233, 1159, 9599, 2870,  924],
       [   0,    0,    0, 2548, 5557, 7328, 4812, 6739],
       [   0,    0,    0,    0, 9995, 1447,  524, 2870]], dtype=int32)

In [34]:
## feature reprentation
dimensions = 10

In [35]:
model = Sequential()
model.add(Embedding(voc_size, dimensions, input_length=sent_length))
model.compile('adam', 'mse')

In [36]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 344ms/step


array([[[-0.04400331, -0.02618682, -0.00377243, -0.00627556,
          0.01951145, -0.0474331 ,  0.03789321,  0.00986518,
         -0.0050143 ,  0.01537044],
        [-0.04400331, -0.02618682, -0.00377243, -0.00627556,
          0.01951145, -0.0474331 ,  0.03789321,  0.00986518,
         -0.0050143 ,  0.01537044],
        [-0.04400331, -0.02618682, -0.00377243, -0.00627556,
          0.01951145, -0.0474331 ,  0.03789321,  0.00986518,
         -0.0050143 ,  0.01537044],
        [-0.04400331, -0.02618682, -0.00377243, -0.00627556,
          0.01951145, -0.0474331 ,  0.03789321,  0.00986518,
         -0.0050143 ,  0.01537044],
        [-0.01980962,  0.00962333, -0.00752263, -0.01202565,
         -0.01311735,  0.01982759, -0.04703284,  0.01893444,
          0.04591291,  0.01859279],
        [-0.0422855 ,  0.02369377, -0.01165221, -0.03807478,
          0.03988649, -0.01699283,  0.00295808,  0.04050915,
         -0.03179266,  0.01572395],
        [ 0.03060644,  0.04852227, -0.04600059, -0.0

In [38]:
embedded_docs[0]

array([   0,    0,    0,    0, 5557, 5493, 4812, 2591], dtype=int32)

In [41]:
model.predict(embedded_docs[0].reshape(1, sent_length))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step


array([[[-0.04400331, -0.02618682, -0.00377243, -0.00627556,
          0.01951145, -0.0474331 ,  0.03789321,  0.00986518,
         -0.0050143 ,  0.01537044],
        [-0.04400331, -0.02618682, -0.00377243, -0.00627556,
          0.01951145, -0.0474331 ,  0.03789321,  0.00986518,
         -0.0050143 ,  0.01537044],
        [-0.04400331, -0.02618682, -0.00377243, -0.00627556,
          0.01951145, -0.0474331 ,  0.03789321,  0.00986518,
         -0.0050143 ,  0.01537044],
        [-0.04400331, -0.02618682, -0.00377243, -0.00627556,
          0.01951145, -0.0474331 ,  0.03789321,  0.00986518,
         -0.0050143 ,  0.01537044],
        [-0.01980962,  0.00962333, -0.00752263, -0.01202565,
         -0.01311735,  0.01982759, -0.04703284,  0.01893444,
          0.04591291,  0.01859279],
        [-0.0422855 ,  0.02369377, -0.01165221, -0.03807478,
          0.03988649, -0.01699283,  0.00295808,  0.04050915,
         -0.03179266,  0.01572395],
        [ 0.03060644,  0.04852227, -0.04600059, -0.0